name: build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        check-latest: true
    - name: build
      run: |
        npm install -D
        npx eslint './src/*.{ts,tsx}'
        npm run build
    - name: test
      run: |
        npm run test:nowatch
